/**
 * data.js — Catálogo de produtos ShopWave
 * Em um projeto real, estes dados viriam de uma API REST.
 */
const PRODUCTS = [
  {
    id: 1,
    name: "Fone Bluetooth Pro X",
    category: "electronics",
    price: 349.90,
    originalPrice: 499.90,
    rating: 4.8,
    reviews: 128,
    badge: "30% OFF",
    emoji: "🎧",
    description: "Som imersivo com cancelamento de ruído ativo e 40h de bateria.",
  },
  {
    id: 2,
    name: "Smartwatch Fit Ultra",
    category: "electronics",
    price: 599.00,
    originalPrice: null,
    rating: 4.6,
    reviews: 89,
    badge: "Novo",
    emoji: "⌚",
    description: "Monitor cardíaco, GPS integrado e resistência à água até 50m.",
  },
  {
    id: 3,
    name: "Tênis Runner 360",
    category: "sports",
    price: 289.90,
    originalPrice: 389.90,
    rating: 4.9,
    reviews: 214,
    badge: "Best Seller",
    emoji: "👟",
    description: "Amortecimento superior para corridas de longa distância.",
  },
  {
    id: 4,
    name: "Jaqueta Urban Street",
    category: "fashion",
    price: 199.90,
    originalPrice: null,
    rating: 4.5,
    reviews: 67,
    badge: null,
    emoji: "🧥",
    description: "Corte moderno, impermeável e perfeita para o dia a dia.",
  },
  {
    id: 5,
    name: "Luminária LED Smart",
    category: "home",
    price: 129.90,
    originalPrice: 189.90,
    rating: 4.7,
    reviews: 156,
    badge: "31% OFF",
    emoji: "💡",
    description: "16 milhões de cores, controle por voz e app no celular.",
  },
  {
    id: 6,
    name: "Mochila Tech Shield",
    category: "fashion",
    price: 179.90,
    originalPrice: null,
    rating: 4.4,
    reviews: 43,
    badge: null,
    emoji: "🎒",
    description: "Compartimento para notebook até 17\", porta USB e anti-furto.",
  },
  {
    id: 7,
    name: "Garrafa Térmica 1L",
    category: "sports",
    price: 89.90,
    originalPrice: 129.90,
    rating: 4.8,
    reviews: 302,
    badge: "Hot",
    emoji: "🧴",
    description: "Mantém quente por 18h e frio por 24h. Aço inoxidável.",
  },
  {
    id: 8,
    name: "Teclado Mecânico RGB",
    category: "electronics",
    price: 449.00,
    originalPrice: null,
    rating: 4.9,
    reviews: 78,
    badge: "Novo",
    emoji: "⌨️",
    description: "Switches Blue, iluminação RGB por tecla e build em alumínio.",
  },
  {
    id: 9,
    name: "Vaso Minimalista",
    category: "home",
    price: 59.90,
    originalPrice: null,
    rating: 4.3,
    reviews: 29,
    badge: null,
    emoji: "🪴",
    description: "Design escandinavo, cerâmica artesanal. Perfeito para suculentas.",
  },
  {
    id: 10,
    name: "Bicicleta Speed Pro",
    category: "sports",
    price: 1899.00,
    originalPrice: 2399.00,
    rating: 4.7,
    reviews: 55,
    badge: "21% OFF",
    emoji: "🚴",
    description: "Quadro de carbono leve, 21 marchas e freios a disco hidráulicos.",
  },
  {
    id: 11,
    name: "Óculos de Sol Wave",
    category: "fashion",
    price: 149.90,
    originalPrice: null,
    rating: 4.6,
    reviews: 91,
    badge: null,
    emoji: "🕶️",
    description: "Proteção UV400, armação acetato italiano e lentes polarizadas.",
  },
  {
    id: 12,
    name: "Mouse Sem Fio Ergo",
    category: "electronics",
    price: 199.90,
    originalPrice: 249.90,
    rating: 4.5,
    reviews: 112,
    badge: "20% OFF",
    emoji: "🖱️",
    description: "Design ergonômico, 4000 DPI e bateria recarregável por USB-C.",
  },
];
